steps:
  # --- Backend: Install, Build, Deploy ---
  - name: 'node:20'
    dir: 'backend'
    entrypoint: npm
    args: ['ci']
    id: 'backend-install'

  - name: 'node:20'
    dir: 'backend'
    entrypoint: npm
    args: ['run', 'build']
    id: 'backend-build'
    waitFor: ['backend-install']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'backend'
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - api
      - '--gen2'
      - '--runtime=nodejs20'
      - '--region=southamerica-east1'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--entry-point=api'
      - '--source=.'
      - '--set-secrets=GEMINI_API_KEY=GEMINI_API_KEY:latest'
      - '--memory=512Mi'
      - '--timeout=120s'
    id: 'backend-deploy'
    waitFor: ['backend-build']

  # --- Frontend: Install, Build, Deploy to Cloud Storage ---
  - name: 'node:20'
    entrypoint: npm
    args: ['ci']
    id: 'frontend-install'

  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    id: 'frontend-build'
    waitFor: ['frontend-install']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gsutil
    args: ['-m', 'rsync', '-r', '-d', 'dist/', 'gs://auto-genius-frontend/']
    id: 'frontend-deploy'
    waitFor: ['frontend-build']

  # --- Deploy Firestore Rules ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - firestore
      - databases
      - update
      - '--type=firestore-native'
    id: 'firestore-rules'

timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
